// Package templates scaffolds new IterForge projects from embedded skeletons.
//
// Layout under files/:
//   - _shared/      files common to every template (go.mod, Makefile, cmd, logs)
//   - <template>/   files specific to one workflow (candidate, evaluator,
//     golden set, policy, docs)
//
// A project is generated by writing the _shared layer then the chosen template
// layer on top. Template files carry a .tmpl suffix so the parent module's
// build, vet, and test never pick them up as source. On generation the suffix
// is stripped and the __MODULE__ placeholder is substituted.
package templates

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed all:files
var templateFS embed.FS

const (
	modulePlaceholder = "__MODULE__"
	sharedLayer       = "_shared"

	// DefaultTemplate is used when no template is requested.
	DefaultTemplate = "text-normalization"
)

// Available returns the selectable template names (every files/ subdirectory
// except the shared layer), sorted.
func Available() []string {
	entries, err := fs.ReadDir(templateFS, "files")
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() && e.Name() != sharedLayer {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	return names
}

func isAvailable(tmpl string) bool {
	for _, n := range Available() {
		if n == tmpl {
			return true
		}
	}
	return false
}

// Init writes a new project named name into parent using the named template.
// It refuses to write into a non-empty destination, and errors on an unknown
// template. The Go module of the generated project is name.
func Init(name, parent, tmpl string) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("project name is required")
	}
	if tmpl == "" {
		tmpl = DefaultTemplate
	}
	if !isAvailable(tmpl) {
		return fmt.Errorf("unknown template %q; available: %s", tmpl, strings.Join(Available(), ", "))
	}

	root := filepath.Join(parent, name)
	if entries, err := os.ReadDir(root); err == nil && len(entries) > 0 {
		return fmt.Errorf("destination %s already exists and is not empty", root)
	}

	for _, layer := range []string{sharedLayer, tmpl} {
		if err := writeLayer(layer, name, root); err != nil {
			return err
		}
	}
	return nil
}

// writeLayer copies one embedded layer (files/<layer>/...) into root, stripping
// the .tmpl suffix and substituting the module placeholder.
func writeLayer(layer, module, root string) error {
	base := "files/" + layer
	return fs.WalkDir(templateFS, base, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		data, err := templateFS.ReadFile(path)
		if err != nil {
			return err
		}
		rel := strings.TrimSuffix(strings.TrimPrefix(path, base+"/"), ".tmpl")
		out := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return err
		}
		content := strings.ReplaceAll(string(data), modulePlaceholder, module)
		return os.WriteFile(out, []byte(content), 0o644)
	})
}
